### PR TITLE
Simple C bare-metal examples and minimal whisper simulator support

### PR DESCRIPTION
**Pull request by luispimo**
**Bare-metal examples**
`native-bare_c`: pure bare-metal (without any library support) C version of the asm example (i.e. simple loop reading switches and writing leds) 
`native-bare_c_whisper`: simple C program without I/O interaction or library support. Since the default debugger init commands fails, I reduced them to the minimum using the debug_init_cmds option.

**Whisper simulator support**
To start the simulator just run the target "start_whisper", then it acts as gdb server.
Minor issue: it is required to add execution permission to elf file `$PACKAGES_DIR/framework-wd-riscv-sdk/board/whisper/whisper`

### CODE REVIEW

**Comment by valeros** [comment]
Hi @luispimo ! Many thanks for the PR.

I noticed you've added a new platform target for simulator tool called `whisper`. It looks like we don't need that additional target `start_whisper` since GDB can be directly connected to whisper (in contrast to `verilator` which required OpenOCD as an intermediary). It might be a good idea to move the configuration of `whisper` to `platform.py` file and then simply specify `whisper` as the `debug_tool` when it's needed (instead of creating a new example `examples/native-bare_c_whisper`):
```
[env:swervolf_nexys]
platform = chipsalliance
board = swervolf_nexys
board_build.ldscript = ld/link.ld
...
debug_tool = whisper
```

Also, there is only one `whisper` binary for Linux, any plans for Windows and Mac ports?

**Comment by luispimo** [comment]
> Hi @luispimo ! Many thanks for the PR.

You're welcome @valeros 

> I noticed you've added a new platform target for simulator tool called `whisper`. It looks like we don't need that additional target `start_whisper` since GDB can be directly connected to whisper (in contrast to `verilator` which required OpenOCD as an intermediary). It might be a good idea to move the configuration of `whisper` to `platform.py` file and then simply specify `whisper` as the `debug_tool` when it's needed (instead of creating a new example `examples/native-bare_c_whisper`)

Ok. I'll give it a try.

> Also, there is only one `whisper` binary for Linux, any plans for Windows and Mac ports?

The binary is provided by the wd-riscv-sdk framework, I think it may be compiled for windows but I am not sure for Mac.

**Comment by luispimo** [comment]
> > Also, there is only one `whisper` binary for Linux, any plans for Windows and Mac ports?
> 
> The binary is provided by the wd-riscv-sdk framework, I think it may be compiled for windows but I am not sure for Mac.

The compilation of the [Syscall.cpp](https://github.com/westerndigitalcorporation/swerv-ISS/blob/master/Syscall.cpp) file fails on OSX. 

It seems that OS X support remains in the WD ToDo list :-(

```
#ifdef __APPLE__
  // TODO: adapt code for Mac OS.
  ptr += 40;
```

**Comment by luispimo** [comment]
I forgot to mention that Whisper code seems to be prepared for compilation on Windows (MINGW64).

**Comment by luispimo** [comment]
> It might be a good idea to move the configuration of `whisper` to `platform.py` file and then simply specify `whisper` as the `debug_tool` when it's needed (instead of creating a new example `examples/native-bare_c_whisper`):
> 
> ```
> [env:swervolf_nexys]
> platform = chipsalliance
> board = swervolf_nexys
> board_build.ldscript = ld/link.ld
> ...
> debug_tool = whisper
> ```
> 

Done!

Do I have to ask a pull request again?

**Comment by valeros** [comment]
Thanks, you don't need to submit a new PR, I'll check the changes and let you know if there is anything could be changed.

**Comment by valeros** [comment]
Thanks!

**Pull request merged**
